### ISSUE TITLE
Одиночная игра на iPad

### ISSUE THREAD

**Issue by VegK** [spbsmile/CavemanUnity5#5]
1. Открываю игру, вижу главный экран
2. Жму Single
3. Экран загрузки
4. Вижу следующее:
   ![img_0012](https://cloud.githubusercontent.com/assets/14677324/10851689/97d1b3f6-7f80-11e5-8f08-08b9b460ae91.jpg)
   Нет ни одного персонажа.
   Джойстик работает, но персонажа нет.
   По окончанию времени вылазит пустой список игроков.

**Comment by spbsmile** [comment]
Обидно , что первая сборка у тебя с багом. 
Так как мир генериться из EnterPoint , то такая бага характерна , когда что-то ломается и камера зависает. Ошибка может быть любая по характеру. Где-то в enterpoint мб что-то сломалось.
При собирании билда полезно жать на галку development build и тогда характер ошибки можно выяснить.

**Comment by VegK** [comment]
Причина в загрузке настроек из Resource:
Caveman.Setting.SettingsHandler.ParseSettingsFromFile
Они просто не грузятся выдавая NULL.
Не было ли подобной проблемы на Android устройствах?

**Comment by VegK** [comment]
Пока что будем юзать [расширенную версию MiniJSON](https://github.com/VegK/MiniJSON), работает - проверено на iPad и iPhone (iOS 9.1).
commit: https://github.com/spbsmile/CavemanUnity5/commit/049edb20e87ed789287313cbe8409292fa3d0514
