### ISSUE TITLE
Глюки графики

### ISSUE THREAD

**Issue by DmitriyKirakosyan** [spbsmile/CavemanUnity5#6]
Графика глючит на некоторых девайсах. Выглядит это [Так](http://answers.unity3d.com/questions/1077723/513-weird-graphic-glitch-on-some-android-devices.html).

**Comment by spbsmile** [comment]
Ideally texture sizes should be powers of two on the sides. These sizes are as follows: 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024 or 2048 pixels. The textures do not have to be square, i.e. width can be different from height.
It is possible to use other (non power of two) texture sizes with Unity. Non power of two texture sizes work best when used on GUI Textures, however if used on anything else they will be converted to an uncompressed RGBA 32 bit format. That means they will take up more video memory (compared to PVRT(iOS)/DXT(Desktop) compressed textures), will be slower to load and slower to render (if you are on iOS mode). In general you'll use non power of two sizes only for GUI purposes. (c)
